// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp1.Data;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20240407144616_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("WinFormsApp1.Entity.EmployeeMaster", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeExt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StaffTypeId");

                    b.ToTable("EmployeeMaster");
                });

            modelBuilder.Entity("WinFormsApp1.Entity.StaffType", b =>
                {
                    b.Property<int>("StaffTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StaffTypeId");

                    b.ToTable("StaffType");

                    b.HasData(
                        new
                        {
                            StaffTypeId = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            StaffTypeId = 2,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("WinFormsApp1.Entity.EmployeeMaster", b =>
                {
                    b.HasOne("WinFormsApp1.Entity.EmployeeMaster", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("WinFormsApp1.Entity.StaffType", "StaffType")
                        .WithMany()
                        .HasForeignKey("StaffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("StaffType");
                });
#pragma warning restore 612, 618
        }
    }
}
